version: '3.8'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/k12_lms.db
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - SECRET_KEY=docker-secret-key-change-in-production
      - ALLOWED_ORIGIN=http://localhost:3000
      - API_VERSION=1.0.0
      - ENVIRONMENT=docker
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:8000/api
      - NEXT_PUBLIC_ENVIRONMENT=docker
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  sqlite_data:
